- name: Add Tower Cloud Credential
  tower_credential:
    name: "{{ tower_cloud_credential }}"
    description: "{{ tower_cloud_credential_description }}"
    kind: "{{ tower_cloud_credential_kind }}"
    organization: "{{ tower_org }}"
    state: present
    username: "{{ tower_cloud_credential_username }}"
    password: "{{ tower_cloud_credential_password }}"
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
  when: tower_cloud_credential|bool == true
