- name: Stage {{ tower_machine_credential }} Private Key
  synchronize:
    src: "{{ tower_machine_credential_ssh_key_data }}"
    dest: "/tmp/{{ tower_machine_credential_ssh_key_data }}"
  when: tower_machine_credential_config|bool == true

- name: Add Tower Machine Credential
  tower_credential:
    name: "{{ tower_machine_credential }}"
    description: "{{ tower_machine_credential_description }}"
    kind: "{{ tower_machine_credential_kind }}"
    organization: "{{ tower_org }}"
    state: present
    ssh_key_data: "/tmp/{{ tower_machine_credential_ssh_key_data }}"
    username: "{{ tower_machine_credential_username }}"
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
  when: tower_machine_credential_config|bool == true

- name: Remove {{ tower_machine_credential }} staging file
  file:
    path: "/tmp/{{ tower_machine_credential_ssh_key_data }}"
    state: absent
  when: tower_machine_credential_config|bool == true
