- name: Configure Job Template for Deploy-Provision
  tower_job_template:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    job_type: run
    name: "{{ tower_job_template_deploy_provision }}"
    description: "{{ tower_job_template_deploy_provision_description }}"
    state: present
    inventory: "{{ tower_inventory }}"
    cloud_credential: "{{ tower_cloud_credential }}"
    project: "{{ tower_project_provision_and_configure }}"
    playbook: "{{ tower_job_template_deploy_provision_playbook }}"
    machine_credential: "{{ tower_machine_credential }}"
  when: tower_job_template_deploy_provision_config|bool == true

- name: Copy Job Template for Deploy-Provision Extra Variables file
  template:
    src: "{{ tower_job_template_deploy_provision_extra_vars_path }}"
    dest: "/tmp/{{ tower_job_template_deploy_provision_extra_vars_path }}"
  when: tower_job_template_deploy_provision_config|bool == true

- name: Update Job Template for Deploy-Provision with Extra Vars
  command: >
    tower-cli job_template modify
      --name="{{ tower_job_template_deploy_provision }}"
      --extra-vars="@/tmp/{{ tower_job_template_deploy_provision_extra_vars_path }}"
      "{{ tower_cli_verbosity }}"
  when: tower_job_template_deploy_provision_config|bool == true
